### ISSUE TITLE
Small problems with generator.py

### ISSUE THREAD

**Issue by ClaudeCoulombe** [shaohua0116/Relation-Network-Tensorflow#1]
The N_GRID value is not set in the generator.py, I've set it to 256 but I'm not sure. Also line 53 seems a typo x = idx_coor[i] % NGRID_ should be x = idx_coor[i] % N_GRID 

Then when I try python trainer.py it raises ValueError('num_outputs should be int or long, got %s.', num_outputs) ValueError: ('num_outputs should be int or long, got %s.', 10) maybe it's related to my N_GRID guess... ;)

num_outputs is 10 <class 'numpy.int64' at 0x102e01418> a NumPy type but the TensorFlow library is expecting regular int or long type

**Comment by shaohua0116** [comment]
Thanks for reporting issues.

The variable N_GRID should be imported from vqa_util.py. I corrected the typo and pushed the code. The generator should work just fine.

**Comment by ClaudeCoulombe** [comment]
Generation works now!
