### ISSUE TITLE
Test on CLEVR

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#10]
If I want to test on CLEVR, what is the difference of these codes,mainly modifying what files???
Thank you~

**Comment by shaohua0116** [comment]
Please note that this should not be reported here as an issue. To implement CLEVR, please refer to the paper.

**Comment by Victoria2333** [comment]
Sorry,i don't know this cannot be an issue......thank you for your kindness~~~
