### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'pretrain_saver'

### ISSUE THREAD

**Issue by Pierre-Wong** [shaohua0116/Relation-Network-Tensorflow#4]
There are some errors when I want to restore the model from checkpoint.
I changed 'self.pretrain_saver.restore(self.session, self.ckpt_path)'
to ' self.saver.restore(self.session, self.ckpt_path) '
It worked.
Is that right?

**Comment by shaohua0116** [comment]
Thanks for raising this issue. You are right. The model should work just fine with this change.
