### ISSUE TITLE
python eval.py:Failed to find any matching files for ckpt_dir

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#6]
I meet some problems
when i run trainer.py,it ends like:
[2017-08-19 11:16:12,451]  [train step   199991] 
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'ScopedTFStatus'",) in <bound method Context.__del__ of <tensorflow.python.eager.context.Context object at 0x7febc2729210>> ignored
when i run eval.py,there shows:
 W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ckpt_dir
So i guess train_dir/baseline-Sort-of-CLEVR_default_lr_0.001-20170619-040301/model-10001
doesn't exist,and i don't know why,please help me ~~~

**Comment by Victoria2333** [comment]
there is only rn-default-Sort-of-CLEVR_default_lr_0.00025-20170817-204422 in train_dir......

**Comment by shaohua0116** [comment]
Could you provide the exact commands (both training and testing) you tried?

**Comment by Victoria2333** [comment]
I did,is the ckpt_dir(train_dir/baseline-Sort-of-CLEVR_default_lr_0.001-20170619-040301/model-10001) created by trainer.py???Because after i run trainer.py,there is only rn-default-Sort-of-CLEVR_default_lr_0.00025-20170819-111519 in trainer_dir......

**Comment by Victoria2333** [comment]
@shaohua0116 
Oh I see,i just need to change the default parameter in trainer.py,and change the model to baseline~~~

**Comment by shaohua0116** [comment]
You can specify the model class that you want to train/test by using the argument `--model`.
