### ISSUE TITLE
How to run your testing with 2,4,6 shapes in one image and your transferring experiment?

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#7]
I see a lot of experiments in ReadMe.md,could you give me some instructions about how to achieve this???

**Comment by shaohua0116** [comment]
You can achieve this by testing trained models on different datasets generated with `generator.py`.
For example, you can train a model with a generated dataset with 4 shapes in each image and then test the model with a dataset with 6 shapes in each image.

**Comment by Victoria2333** [comment]
@shaohua0116 
So i just need to change the variable NUM_SHAPE to 2,4 6 separately in vqa_util.py ,and then python generator.py to get different datasets, am I right???

**Comment by shaohua0116** [comment]
Correct.

**Comment by Victoria2333** [comment]
Thanks~~~
