### ISSUE TITLE
How to use Tensorboard or Tensorflow Plot 

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#8]
As is mentioned,during the training phase, the samples including images, questions, ground truth answers, and predicted answers can be monitored on Tensorboard if the library Tensorflow Plot is installed,how could i operate to monitor this process???
I see tfplot and seaborn two modules in link"Tensorflow Plot",do i need to install seaborn either???
And also if i want to visualize the CNN internal network,what should i do???
Thanks for your guide!!!

**Comment by shaohua0116** [comment]
Please install tfplot with this command 
`pip install git+https://github.com/wookayin/tensorflow-plot.git@master`. 
The detailed document can be found here [tfplot](https://github.com/wookayin/tensorflow-plot). After installing it, you can view the training details on Tensorboard.
