### ISSUE TITLE
.py File Functions

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#9]
Could you please explain all the functions these .py files want to achieve,for example,you use generator.py to generate datasets with different shapes ,what does sort_of_clevr.py want to do???
And what about ops.py, input_ops.py, util.py,vqa_util.py???
Actually reading Class python is hard for me because I am a newer in this field and hope you would help me ,thank you very much~~~

**Comment by shaohua0116** [comment]
`sort_of_clevr.py`: splits datasets into training and testing sets and enables data loading.
`input_ops.py`: provides input batches.
`ops.py`: defines my own operations including conv2d, fc, etc.
`util.py` and `vqa_util.py`: provide utility functions including log info, conversion between answer.question strings and one-hot vectors, etc.

**Comment by Victoria2333** [comment]
Appreciate your help~~~

**Comment by Victoria2333** [comment]
Another question, if I want to test on CLEVR, what is the difference of these codes,mainly modifying what files???
